# Práctica 1 (Curso 2024)
## Seminario de Mecánica Cuántica / Teoría de la Información Cuántica

Voy a hacer el ejercicio

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

In [2]:
!pip install qutip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.0/28.0 MB 2.6 MB/s eta 0:00:0000:0100:01


Para usar QuTiP en un programa de Python, se incluye el modulo `qutip` al principio:

In [3]:
from qutip import *

In [4]:
from sympy import init_printing
init_printing(use_latex=True)

Esto habilita las funciones y clases de QuTiP en el resto del programa.

## Quantum object class: `qobj`

`Qobj` class, which is used for representing quantum object such as states and operator. 

The `Qobj` class contains all the information required to describe a quantum system, such as its matrix representation, composite structure and dimensionality. 

## Estados 

Create a new quantum object using the `Qobj` class constructor, like this:

### Base Estandar 1-qubit

$|0\rangle$

In [5]:
st0 = Qobj([[1], [0]])

st0

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

In [6]:
st1 = Qobj([[0], [1]])

st1

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]

Here we passed python list as an argument to the class constructor. The data in this list is used to construct the matrix representation of the quantum objects, and the other properties of the quantum object is by default computed from the same data.

We can inspect the properties of a `Qobj` instance using the following class method:

In [7]:
# the dimension, or composite Hilbert state space structure
st0.dims

In [8]:
# the shape of the matrix data representation
st0.shape

In [9]:
# the matrix data itself. in sparse matrix format. 
st0.data

Dense(shape=(2, 1), fortran=True)

In [10]:
# get the dense matrix representation
st0.full()

array([[1.+0.j],
       [0.+0.j]])

In [7]:
# some additional properties
st0.isherm, st0.type 

(False, 'ket')

### Base estandar 2-qubits

In [11]:
st00=tensor(st0,st0);
st01=tensor(st0,st1);
st10=tensor(st1,st0);
st11=tensor(st1,st1);
 
st00


Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [12]:
st01

Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [13]:
Psi00=(st00+st11)/np.sqrt(2); Psi00 #estado de Bell

Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

##  Matrices Densidad

In [14]:
rho0=st0*st0.dag();rho0 # Proyector |0><0| de un qubit
rho0tilde=ket2dm(st0) #otra forma
rho0tilde

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [15]:
rho0

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [16]:
rho00 = st00 * st00.dag();rho00 #Proyector |00><00| de dos qubits

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

## Parte II: Estados de sistemas compuestos. Entrelazamiento

### II.1 Para un sistema de dos qubits, escribir explícitamente la matriz que representa a $\rho_{AB}=|\Phi_{AB}\rangle\langle\Phi_{AB}|$ en la base computacional $\{|00\rangle,|01\rangle,|10\rangle,|11\rangle\}$ para:

$a)|\Phi_{AB}\rangle=\frac{|00\rangle\pm|11\rangle}{\sqrt{2}}\,,\;\;\;\;\;\;$
$b) \;|\Psi_{AB}\rangle=\frac{|00\rangle+|10\rangle-|01\rangle-|11\rangle}{2}$

Verificar  en todos los casos que los autovalores de $\rho$ son $(1,0,0,0)$.

In [17]:
rhoPsi00 = Psi00 * Psi00.dag();rhoPsi00 

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

In [24]:
rhoPsi00

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

In [27]:
rhoPsi00a=np.array([[1,0,0,1],[0,0,0,0],[0,0,0,0],[1,0,0,1]])/(2)
rhoPsi00a

array([[0.5, 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.5]])

In [28]:
# eigenvalues and eigenvectors
e,v = np.linalg.eig(rhoPsi00a)
print("Eigenvalues:",e)
print("Eigenvectors:",v)

Eigenvalues: [1.00000000e+00 1.11022302e-16 0.00000000e+00 0.00000000e+00]
Eigenvectors: [[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.          0.        ]]


### II.2 Hallar la matriz densidad reducida $\rho_A={\rm Tr}_B\rho_{AB}$ en todos los casos anteriores, y a partir de ella evaluar la entropía de entrelazamiento del estado.

In [19]:
rhored=rhoPsi00.ptrace(1);rhored #estado reducido

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]

In [20]:
p_0=p_1=0.5

E = -(p_0*np.log2(p_0) + p_1*np.log2(p_1))

print("Es máximamente entrelazado:E(A,B)=",E)

Es máximamente entrelazado:E(A,B)= 1.0


### II.3  Hallar la descomposición de Schmidt de los estados anteriores.

a) El estado $|\Phi_{AB}\rangle=\frac{|00\rangle+|11\rangle}{\sqrt{2}}$ ya se encuentra en la descomposición de Schmidt

In [21]:
Psi00

Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [22]:
C00=np.array([[1,0],[0,1]])/np.sqrt(2) #Matriz de coeficientes para el estado Psi00
C00

array([[0.70710678, 0.        ],
       [0.        , 0.70710678]])

In [23]:
U,D,V=np.linalg.svd(C00)
V

array([[1., 0.],
       [0., 1.]])

### II.4 Para $|\alpha|^2+|\beta|^2=1$, hallar la descomposición de Schmidt del estado  $|\Psi_{AB}\rangle=\alpha\frac{|00\rangle+|11\rangle}{\sqrt{2}}+\beta
\frac{|01\rangle+|10\rangle}{\sqrt{2}}$

In [29]:
import sympy

In [30]:
from sympy import *
init_printing(use_latex='mathjax')
x, y, z = symbols('x,y,z')
r, theta = symbols('r,theta', positive=True)
alpha, beta = symbols('alpha,beta', positive=True)

In [31]:
vec = np.array([[alpha/sympy.sqrt(2)],[beta/sympy.sqrt(2)],[beta/sympy.sqrt(2)],[alpha/sympy.sqrt(2)]])

In [32]:
vec

array([[sqrt(2)*alpha/2],
       [sqrt(2)*beta/2],
       [sqrt(2)*beta/2],
       [sqrt(2)*alpha/2]], dtype=object)

In [33]:
rho4 = vec @ vec.T.conj()
rho4

array([[alpha**2/2, alpha*beta/2, alpha*beta/2, alpha**2/2],
       [alpha*beta/2, beta**2/2, beta**2/2, alpha*beta/2],
       [alpha*beta/2, beta**2/2, beta**2/2, alpha*beta/2],
       [alpha**2/2, alpha*beta/2, alpha*beta/2, alpha**2/2]], dtype=object)

In [34]:
rho4_A =Matrix([[alpha**2/2 + beta**2/2, -alpha*beta], [-alpha*beta, alpha**2/2 + beta**2/2]]) #Matriz Reducida

In [35]:
rho4_A

⎡ 2    2         ⎤
⎢α    β          ⎥
⎢── + ──   -α⋅β  ⎥
⎢2    2          ⎥
⎢                ⎥
⎢          2    2⎥
⎢         α    β ⎥
⎢ -α⋅β    ── + ──⎥
⎣         2    2 ⎦

In [36]:
rho4_A.eigenvals() 

⎧ 2          2      2          2   ⎫
⎪α          β      α          β    ⎪
⎨── - α⋅β + ──: 1, ── + α⋅β + ──: 1⎬
⎪2          2      2          2    ⎪
⎩                                  ⎭

In [37]:
C4=Matrix([[alpha/sympy.sqrt(2),beta/sympy.sqrt(2)],[beta/sympy.sqrt(2),alpha/sympy.sqrt(2)]]) #Matriz de coeficientes para el estado Psi00
C4

⎡√2⋅α  √2⋅β⎤
⎢────  ────⎥
⎢ 2     2  ⎥
⎢          ⎥
⎢√2⋅β  √2⋅α⎥
⎢────  ────⎥
⎣ 2     2  ⎦

In [38]:
C4.singular_values()

⎡     _______________       _______________⎤
⎢    ╱  2          2       ╱  2          2 ⎥
⎢   ╱  α          β       ╱  α          β  ⎥
⎢  ╱   ── + α⋅β + ── ,   ╱   ── - α⋅β + ── ⎥
⎣╲╱    2          2    ╲╱    2          2  ⎦

### II.5 a) Indicar en qué se diferencian el estado de Bell $|\Psi_{AB}\rangle=\frac{|01\rangle+|10\rangle}{\sqrt{2}}$ y el estado descripto por el operador densidad $\rho_{AB}=\frac{1}{2}(|01\rangle\langle 01|+|10\rangle\langle 10|)$ 
### b) Indicar si es posible distinguirlos mediante:
### i) el valor medio de un observable local $ O_A\otimes I_B$. 
### ii) el valor medio de un observable $O=O_A\otimes O_B$. 

### Using `Qobj` instances for calculations

With `Qobj` instances we can do arithmetic and apply a number of different operations using class methods:

In [39]:
sy = Qobj([[0,-1j], [1j,0]])  # the sigma-y Pauli operator

sy

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

In [40]:
sz = Qobj([[1,0], [0,-1]]) # the sigma-z Pauli operator

sz

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [12]:
# some arithmetic with quantum objects

H = 1.0 * sz + 0.1 * sy

print("Qubit Hamiltonian = \n")
H

Qubit Hamiltonian = 



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

Example of modifying quantum objects using the `Qobj` methods:

In [13]:
# The hermitian conjugate
sy.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [14]:
# The trace
H.tr()

0.0

In [15]:
# Eigen energies
H.eigenenergies()

array([-1.00498756,  1.00498756])

## Operators

### Operadores de un Qubit : Matrices de Pauli

In [12]:
# Pauli sigma x
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [23]:
# Pauli sigma y
sigmay()

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.+0.j  0.-1.j]
 [ 0.+1.j  0.+0.j]]

In [24]:
# Pauli sigma z
sigmaz()

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

Conmutador matrices de Pauli 

$[\sigma_x, \sigma_y] = 2i \sigma_z$

In [33]:
-1j * sigmax() * sigmay() * sigmaz()

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]]

$\sigma_x^2 = \sigma_y^2 = \sigma_z^2 = \mathbf{1}$

In [34]:
sigmax()**2 == sigmay()**2 == sigmaz()**2 == qeye(2)

True